#!/bin/bash

clear;

echo -e "==> Give app name\n"
read -p "APP name: " APP_NAME

if [ -z $APP_NAME ]; then
  echo -e "App name can't be blank\n"
  echo -e "Exiting..."

  exit 0
else
  docker-compose run --rm $APP_NAME sh -c "gem install rails; \
    rails new . \
    --api \
    --database=postgresql \
    --skip-bundle \
    --skip-test"
fi

if [ ! -f "./.env" ]; then
  cp ./sample.env ./.env
fi
